# Generated by Django 4.0.3 on 2022-04-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена после скидки'),
        ),
    ]
