# Generated by Django 4.0.3 on 2022-04-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/news/%Y/%m/%d')),
                ('title', models.CharField(max_length=100, verbose_name='News')),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
    ]
