# Generated by Django 4.0.3 on 2022-04-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_size_line_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size_line_number',
            field=models.IntegerField(),
        ),
    ]
